AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EC2SG:
    Type: String
  
Resources:
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
      InstanceType: t3.medium
      ImageId: ami-0b5eea76982371e91
      SecurityGroupIds:
        - !Ref EC2SG
      SubnetId: subnet-01ad7291af69ab2e2

Outputs:
  EC2Resource:
    Description: 'EC2 resource'
    Value: !Ref WebInstance
