AWSTemplateFormatVersion: '2010-09-09'
Description: |
  AWS CloudFormation creates IAM Permissions template. These resources grant permissions for every IAM role for EKS/Fargate Base

Parameters:

  StackEnvironment:
    Type: String
    Description: 'Clave del ambiente donde se esta haciendo el despliegue en mayusculas (DE, Q, PD)'

  AppPrefix:
    Type: String
    Description: 'Prefijo del aplicativo de acuerdo a la nomenclatura de AMX en letras mayusculas (ej. AMX-APP)'
    Default: ''

  EksRoleName:
    Type: String
    Description: 'Sufijo de rol de EKS de acuerdo a la nomenclatura de AMX en letras mayusculas (ej. EKS-PERMISSIONS)'
    Default: ''

  FargateExecutionRoleName:
    Type: String
    Description: 'Sufijo de rol de Fargate de acuerdo a la nomenclatura de AMX en letras mayusculas (ej. FARGATE-PERMISSIONS)'
    Default: ''
    
  # Tags
  AreaResponsable:
    Type: String
    Description: Area responsable
    Default: ''

  CentroDeCosto:
    Type: String
    Description: Centro de Costos asociados a TI
    Default: ""

  DuenoDeLaCuenta:
    Type: String
    Description: Lista de distribucion asociada
    Default: ""

  Proyecto:
    Type: String
    Description: Nombre oficial de OU padre
    Default: ""

  Aplicacion:
    Type: String
    Description: Nombre de aplicacion oficial
    Default: ""

  ImpactoANegocio:
    Type: String
    Description: Impacto de negocio
    Default: ""

Resources:

  CloudWatchWriteAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Política que permite la escritura de logs desde el aplicativo alojado en eks
      ManagedPolicyName: !Sub ${AppPrefix}-${StackEnvironment}-CW-LOGS'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogStream'
              - 'logs:DescribeLogGroups'
              - 'logs:DescribeLogStreams'
              - 'logs:CreateLogGroup'
            Resource:
              - !Sub "arn:${AWS::Partition}:logs:*:${AWS::AccountId}:log-group:*"
          - Effect: Allow
            Action:
              - 'logs:PutLogEvents'
            Resource:
              - !Sub "arn:${AWS::Partition}:logs:*:${AWS::AccountId}:log-group:*:log-stream:*"

  S3ReadWriteAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Política que permite la lectura y escritura de archivos desde el aplicativo alojado en eks a buckets de s3
      ManagedPolicyName: !Sub ${AppPrefix}-${StackEnvironment}-S3-READ-WRITE'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:ReplicateObject'
              - 's3:PutObject'
              - 's3:GetObjectAcl'
              - 's3:GetObject'
              - 's3:ReplicateTags'
              - 's3:PutObjectTagging'
              - 's3:DeleteObject'
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::*/*"
  
  SsmKmsReadAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Política que permite la lectura de secretos y uso de kms desde el aplicativo alojado en eks
      ManagedPolicyName: !Sub ${AppPrefix}-${StackEnvironment}-SSM-KMS-READ'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'secretsmanager:GetResourcePolicy'
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:DescribeSecret'
              - 'secretsmanager:ListSecretVersionIds'
              - 'secretsmanager:TagResource'
              - 'kms:GetParametersForImport'
              - 'kms:GetPublicKey'
              - 'kms:Decrypt'
              - 'kms:GetKeyRotationStatus'
              - 'kms:GetKeyPolicy'
              - 'kms:GenerateDataKey'
              - 'kms:DescribeKey'
            Resource:
              - !Sub "arn:${AWS::Partition}:secretsmanager:*:${AWS::AccountId}:secret:*"
              - !Sub "arn:${AWS::Partition}:kms:*:${AWS::AccountId}:key/*"

  EksIamRole:
    Type: AWS::IAM::Role
    DependsOn: 
      - CloudWatchWriteAccess
      - S3ReadWriteAccess
      - SsmKmsReadAccess
    Properties:
      RoleName: !Sub '${AppPrefix}-${StackEnvironment}-${EksRoleName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
 #       - !Ref CloudWatchWriteAccess
 #       - !Ref S3ReadWriteAccess
 #       - !Ref SsmKmsReadAccess
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      Path: '/'

      Tags:
        - Key: Ambiente
          Value: !Ref StackEnvironment
        - Key: AreaResponsable
          Value: !Ref AreaResponsable
        - Key: CentroDeCosto
          Value: !Ref CentroDeCosto
        - Key: DuenoDeLaCuenta
          Value: !Ref DuenoDeLaCuenta
        - Key: Proyecto
          Value: !Ref Proyecto
        - Key: Aplicacion
          Value: !Ref Aplicacion
        - Key: ImpactoANegocio
          Value: !Ref ImpactoANegocio

  FargateExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppPrefix}-${StackEnvironment}-${FargateExecutionRoleName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks-fargate-pods.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy
      Path: '/'

      Tags:
        - Key: Ambiente
          Value: !Ref StackEnvironment
        - Key: AreaResponsable
          Value: !Ref AreaResponsable
        - Key: CentroDeCosto
          Value: !Ref CentroDeCosto
        - Key: DuenoDeLaCuenta
          Value: !Ref DuenoDeLaCuenta
        - Key: Proyecto
          Value: !Ref Proyecto
        - Key: Aplicacion
          Value: !Ref Aplicacion
        - Key: ImpactoANegocio
          Value: !Ref ImpactoANegocio


Outputs:

  AmxEksIamRoleArn: 
    Description: ARN of EKS Role
    Value: !GetAtt EksIamRole.Arn

  AmxFargateIamRoleArn: 
    Description: ARN of Fargate Role
    Value: !GetAtt FargateExecutionRole.Arn
    