AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template EKS Nested Stack'

Parameters:

  StackEnvironment:
    Type: String
    Description: 'Clave del ambiente donde se esta haciendo el despliegue en mayusculas (DE, Q, PD)'

  AppPrefix:
    Type: String
    Description: 'Prefijo del aplicativo de acuerdo a la nomenclatura de AMX en letras mayusculas (ej. AMX-APP)'
    Default: ''

  EKSClusterName:
    Type: String
    Description: Nombre de EKS Cluster
    Default: ''

  EKSClusterVersion:
    Type: String
    Description: Version de EKS Cluster
    Default: ''

  EksCmk:
    Type: String
    Description: ARN de Llave EKS
    Default: ''

  ControlPlaneIamRole:
    Type: String
    Description: Rol de EKS - Control Plane
    Default: ''

  EksVpcId:
    Type: String
    Description: VPC Id para EKS Cluster
    Default: ''

  VpcCidr:
    Type: String
    Description: Cidr de VPC
    Default: ''

  ControlPlaneCidr:
    Type: String
    Description: Cidr de Control Plane
    Default: ''

  PrivateSubnetId1:
    Type: String
    Description: Id de subred privada 1
    Default: ''

  PrivateSubnetId2:
    Type: String
    Description: Id de subred privada 2
    Default: ''
  
  # Tags
  AreaResponsable:
    Type: String
    Description: Area responsable
    Default: Operaciones

  CentroDeCosto:
    Type: String
    Description: Centro de Costos asociados a TI
    Default: ""

  DuenoDeLaCuenta:
    Type: String
    Description: Lista de distribucion asociada
    Default: ""

  Proyecto:
    Type: String
    Description: Nombre oficial de OU padre
    Default: ""

  Aplicacion:
    Type: String
    Description: Nombre de aplicacion oficial
    Default: ""

  ImpactoANegocio:
    Type: String
    Description: Impacto de negocio
    Default: ""
 

Resources:
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Control Plane
      VpcId: !Ref EksVpcId

      Tags:
        - Key: Ambiente
          Value: !Ref StackEnvironment
        - Key: AreaResponsable
          Value: !Ref AreaResponsable
        - Key: CentroDeCosto
          Value: !Ref CentroDeCosto
        - Key: DuenoDeLaCuenta
          Value: !Ref DuenoDeLaCuenta
        - Key: Proyecto
          Value: !Ref Proyecto
        - Key: Aplicacion
          Value: !Ref Aplicacion
        - Key: ImpactoANegocio
          Value: !Ref ImpactoANegocio
  
  ControlPlaneSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn:
      - ControlPlaneSecurityGroup
    Properties:
      GroupId: !Ref ControlPlaneSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: !Ref VpcCidr

  ControlPlaneSecurityEgressGroup:
    Type: AWS::EC2::SecurityGroupEgress
    DependsOn:
      - ControlPlaneSecurityGroup
    Properties:
      GroupId: !Ref ControlPlaneSecurityGroup
      CidrIp: !Ref VpcCidr
      FromPort: 10250
      ToPort: 65535
      IpProtocol: tcp

  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub '${AppPrefix}-${StackEnvironment}-${EKSClusterName}'
      Version: !Ref EKSClusterVersion
      RoleArn: !Ref ControlPlaneIamRole
      EncryptionConfig:
        - Provider:
            KeyArn:
              !Ref EksCmk
          Resources:
          - secrets
      KubernetesNetworkConfig:
        ServiceIpv4Cidr: !Ref ControlPlaneCidr
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetId1
          - !Ref PrivateSubnetId2
        EndpointPrivateAccess: true
        EndpointPublicAccess: false
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
            - Type: authenticator
            - Type: controllerManager
            - Type: scheduler

      Tags:
        - Key: Ambiente
          Value: !Ref StackEnvironment
        - Key: AreaResponsable
          Value: !Ref AreaResponsable
        - Key: CentroDeCosto
          Value: !Ref CentroDeCosto
        - Key: DuenoDeLaCuenta
          Value: !Ref DuenoDeLaCuenta
        - Key: Proyecto
          Value: !Ref Proyecto
        - Key: Aplicacion
          Value: !Ref Aplicacion
        - Key: ImpactoANegocio
          Value: !Ref 
          

  OidcProvider:
    Type: AWS::IAM::OIDCProvider
    DependsOn:
      - EksCluster
    Properties: 
      Url: !GetAtt EksCluster.OpenIdConnectIssuerUrl
      ThumbprintList: 
        - 9e99a48a9960b14926bb7f3b02e22da2b0ab7280
      ClientIdList:
        - sts.amazonaws.com

      Tags:
        - Key: Ambiente
          Value: !Ref StackEnvironment
        - Key: AreaResponsable
          Value: !Ref AreaResponsable
        - Key: CentroDeCosto
          Value: !Ref CentroDeCosto
        - Key: DuenoDeLaCuenta
          Value: !Ref DuenoDeLaCuenta
        - Key: Proyecto
          Value: !Ref Proyecto
        - Key: Aplicacion
          Value: !Ref Aplicacion
        - Key: ImpactoANegocio
          Value: !Ref ImpactoANegocio

Outputs:

  AmxControlPlaneName:
    Description: 'EKS Control Plane'
    Value: !Ref EksCluster
    Export:
      Name: amx-app-eks-name

  AmxControlPlaneOpenIdConnectIssuerUrl:
    Description: 'EKS Control Plane Issue URL'
    Value: !Select [1, !Split ["https://", !GetAtt EksCluster.OpenIdConnectIssuerUrl]]
    Export:
      Name: amx-app-eks-url

  AmxControlPlaneEndpoint:
    Description: 'EKS Control Plane Endpoint'
    Value: !GetAtt EksCluster.Endpoint
    Export:
      Name: amx-app-eks-endpoint

  
