version: 0.2

phases:
  build:
    commands:
      - echo "Validating CFN templates"
      - |
        aws cloudformation validate-template --template-body file://AMX-CA-CC-CF-ROOT-STACK.yaml
        cd templates
        for cfn_template in AMX-CA-CC-DES-CF-*-NESTED-STACK.yaml; do
          echo "Validating CloudFormation template file $cfn_template"
          aws cloudformation validate-template --template-body file://$cfn_template
        done
