version: 0.2

phases:
  build:
    commands:
      - echo "Validating CFN templates"
      - |
        aws cloudformation validate-template --template-body file://AMX-PPL-CC-CF-ROOT-STACK-CF-DES.yaml
        cd templates
        for cfn_template in AMX-PPL-CC-CF-*-NESTED-STACK-CF-DES.yaml; do
          echo "Validating CloudFormation template file $cfn_template"
          aws cloudformation validate-template --template-body file://$cfn_template
        done
