version: 0.2

phases:
  build:
    commands:
      - echo "Validating CFN templates"
      - |
        aws cloudformation validate-template --template-body file://AMX-CA-CF-ROOT-STACK.yaml
        for cfn_template in AMX-CF-CA-*.yaml; do
          echo "Validating CloudFormation template file $cfn_template"
          aws cloudformation validate-template --template-body file://$cfn_template
        done
