version: 0.2
phases:
  install:
    commands:
      - cd /tmp/
      - env
      - wget https://github.com/fw10/veracode-javascript-packager/releases/latest/download/veracode-js-packager-linux-amd64 -O /tmp/veracode-js-packager
      - chmod 755 /tmp/veracode-js-packager
  pre_build:
    commands:
      - ls -l /tmp/
  build:
    commands:
      - /tmp/veracode-js-packager -source $CODEBUILD_SRC_DIR_AppSourceOutput -target /tmp/
      - ls -l /tmp/
      - VC_OUTPUT=$(ls /tmp/vc-output*)
      - echo $VC_OUTPUT
      - |
        if [ "${EXECUTE_SECURITY_SCAN}" = "ON" ]
        then
          curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/23.4.11.2/vosp-api-wrappers-java-23.4.11.2-dist.zip --output /tmp/VeracodeJavaAPI.zip
          unzip /tmp/VeracodeJavaAPI.zip -d /tmp/VeracodeJavaAPI
          java -jar /tmp/VeracodeJavaAPI/VeracodeJavaAPI.jar -action uploadandscan -vid "${VID}" -vkey "${VKEY}" -createprofile false -appname "${VeracodeAPPNAME}" --sandboxname "${VeracodeSANDBOXNAME}" -filepath ${VC_OUTPUT} -version $(date +%d%m%Y-%H%M) -selectedpreviously true
        else
          echo "Vulnerability scan disabled."
        fi
