AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template IAM Roles Nested Stack'
Parameters:
  EKSRoleName:
    Type: String
  FargateExecutionRoleName:
    Type: String

Resources:
  EKSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
            - eks-fargate-pods.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
      Path: '/'
      RoleName: !Ref EKSRoleName
  FargateExecutionRoleArn:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks-fargate-pods.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy
      Path: '/'
      RoleName: !Ref FargateExecutionRoleName
  
Outputs:
  EKSRoleArn:
    Description: 'EKS IAM Role'
    Value: !GetAtt EKSIAMRole.Arn
  FargateExecutionRoleArn:
    Description: 'Fargate Profile IAM Role'
    Value: !GetAtt FargateExecutionRoleArn.Arn